
export const ADD_HOME_REQUEST = 'ADD_HOME_REQUEST';
export const ADD_HOME_SUCCESS = 'ADD_HOME_SUCCESS';
export const ADD_HOME_FAILURE = 'ADD_HOME_FAILURE';

export const DELETE_HOME_REQUEST = 'DELETE_HOME_REQUEST';
export const DELETE_HOME_SUCCESS = 'DELETE_HOME_SUCCESS';
export const DELETE_HOME_FAILURE = 'DELETE_HOME_FAILURE';

export const FIND_HOME_REQUEST = 'FIND_HOME_REQUEST';
export const FIND_HOME_SUCCESS = 'FIND_HOME_SUCCESS';
export const FIND_HOME_FAILURE = 'FIND_HOME_FAILURE';

export const FIND_HOMES_REQUEST = 'FIND_HOMES_REQUEST';
export const FIND_HOMES_SUCCESS = 'FIND_HOMES_SUCCESS';
export const FIND_HOMES_FAILURE = 'FIND_HOMES_FAILURE';

export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const FIND_ITEM_REQUEST = 'FIND_ITEM_REQUEST';
export const FIND_ITEM_SUCCESS = 'FIND_ITEM_SUCCESS';
export const FIND_ITEM_FAILURE = 'FIND_ITEM_FAILURE';

export const FIND_ITEMS_REQUEST = 'FIND_ITEMS_REQUEST';
export const FIND_ITEMS_SUCCESS = 'FIND_ITEMS_SUCCESS';
export const FIND_ITEMS_FAILURE = 'FIND_ITEMS_FAILURE';
