
export const ADD_HOME_REQUEST = 'ADD_HOME_REQUEST';
export const ADD_HOME_SUCCESS = 'ADD_HOME_SUCCESS';
export const ADD_HOME_FAILURE = 'ADD_HOME_FAILURE';

export const DELETE_HOME_REQUEST = 'DELETE_HOME_REQUEST';
export const DELETE_HOME_SUCCESS = 'DELETE_HOME_SUCCESS';
export const DELETE_HOME_FAILURE = 'DELETE_HOME_FAILURE';

export const FIND_HOME_REQUEST = 'FIND_HOME_REQUEST';
export const FIND_HOME_SUCCESS = 'FIND_HOME_SUCCESS';
export const FIND_HOME_FAILURE = 'FIND_HOME_FAILURE';

export const FIND_HOMES_REQUEST = 'FIND_HOMES_REQUEST';
export const FIND_HOMES_SUCCESS = 'FIND_HOMES_SUCCESS';
export const FIND_HOMES_FAILURE = 'FIND_HOMES_FAILURE';
